services:
  web:
    depends_on:
        - mysql
        - backend
    image: nginx:1.19
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
      - "81:8080"
  mysql:
    image: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=fullcycle"
    volumes:
      - data-volume:/var/lib/mysql
  backend:
    build:
      context: ./
    entrypoint: wait-for mysql:3306 -t 40 -- sh /code/start.sh
    volumes:
      - ./backend:/code
    depends_on:
        - mysql
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    command: [sh, -c, "npm install && npm run dev"]
    volumes:
      - ./frontend:/code
    
volumes:
  data-volume:
